site_name: Google Ads API Notes
site_url: https://ads.danielfrg.com
site_author: Daniel Rodriguez
site_description: >-
  Notes on how I do use the Google Ads API
# repo_url: https://github.com/danielfrg/ads.danielfrg.com
copyright: Copyright &copy; 2023 Daniel Rodriguez

nav:
  - Python:
      - Python Snippets: python/index.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search

extra:
  analytics:
    provider: google
    property: G-3673QMK9C4
